immerdev/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

index/urls.py
from django.conf.urls import url
from . import views

app_name = "index"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    #portfolio/pk   - uses a named group which usually takes the format: '?<name>pattern'
    url(r'^portfolio/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^blog/$', views.BlogView.as_view(), name='blog'),

]

index/models.py
from django.db import models
from django.utils import timezone

class Portfolio(models.Model):
    '''
        Holds structure of the Portfolio relation in the DB
    '''
    project_title = models.CharField(max_length=100)
    project_type = models.CharField(max_length=70)
    project_cover_pic = models.ImageField(upload_to='uploads/coverpics/', blank=True)
    client = models.CharField(max_length=150, blank=True)
    status = models.CharField(max_length=50, blank=True)
    project_description = models.TextField(max_length=500, blank=True)
    project_link = models.URLField(blank=True)

    def __str__(self):
        return self.project_title

class Blog(models.Model):
    '''
        Holds structure of the Blog relation in the DB
    '''
    blog_title = models.CharField(max_length=100)
    blog_author = models.CharField(max_length=70)
    author_profile_pic = models.ImageField(upload_to="uploads/authorprofilepics/", blank=True, null=True)
    author_profile = models.TextField(max_length=250)
    author_link_fb = models.URLField(blank=True)
    author_link_li = models.URLField(blank=True)
    author_link_tw = models.URLField(blank=True)
    author_link_ig = models.URLField(blank=True)
    article = models.TextField(max_length=None)
    publish_time = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.blog_title

index/views.py
# from django.shortcuts import render
from django.views import generic
from .models import Portfolio, Blog

class IndexView(generic.ListView):
    '''Returns index with corresponding model val.s'''
    template_name = 'index/main.html'
    context_object_name = 'index_list'
    queryset = Portfolio.objects.all()

class DetailView(generic.DetailView):
    '''returns details for a specific selected project'''
    model = Portfolio
    template_name = 'index/project.html'

class BlogView(generic.ListView):
    '''Returns blog with corresponding model val.s'''
    template_name = 'index/blog_main.html'
    context_object_name = 'blog_list'
    queryset = Blog.objects.all()

index/templates/index/blog_main.html
{% extends 'index/index.html' %}

{% load staticfiles %}
{% block body %}
{% if blog_list %}
    <div class="container">
        <div class="row">
            {% for blog in blog_list %}
            <div class="col-md-4">
                <ul class="blog-details">
                    <li class="blog-title">{{ blog.blog_title }}</li>
                    <li class="blog-author">{{ blog.blog_author }}</li>
                    <li class="pub-time">{{ blog.publish_time }}</li>
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="container" style="text-align:center;margin-top:50px;">
        <h3> Oops!</h3>
        <p> No articles currently available<span style="font-size:10px; color:#9E2222;">...but they're coming</span></p>
    </div>

{% endif %}

{% endblock %}

index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>{% block title%} immerDEV {% endblock %}</title>
    {% load staticfiles %}

    <link href="https://fonts.googleapis.com/css?family=Fira+Mono|Nova+Mono|Roboto+Mono" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='{% static "index/dist/css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "index/main_immer.css" %}' rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-toggleable-md">
        <a class="navbar-brand" href="{% url 'index:index' %}">IMMERdev</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#rightnavbar" aria-controls="rightnavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="rightnavbar">
            <ul class="nav navbar-nav ml-auto">
                <li><a href="{% url 'index:blog' %}">blog</a></li>
                <li><a href="#contact-us">contact us</a></li>
            </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <div class="container contact-us-section" id="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-md-4" style="margin: auto;">
                    <h3>Contact Us</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam, magni!</p>
                </div>
                <div class="col-md-8"
                    <form action="" class="contact-us-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    <div>
                                        <input type="text" class="email" name="email" placeholder="*email address">
                                    </div><br>
                                    <div>
                                        <input type="text" class="subject" name="email-subject" placeholder="*subject">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div>
                                        <textarea name="email-message" rows="5" cols=40 placeholder="*message" ></textarea>
                                    </div>
                                    <div class="">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <hr>
    <footer>
        <div class="container footer-details">
          <div class="row">
            <div class="col-md-4" style="padding:0;">
              <p><span class="	fa fa-phone"></span> Tel: 07123987456</p>
              <p><span class="fa fa-comments"></span> Email: info@immerdev.com</p>
            </div>
            <div class="col-md-4">
              <a href="#"><p> Blog</p></a>
            </div>
          </div>
        </div>
        <p class="copyright-label">&copy; immerdev 2017</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src={% static "index/assets/js/vendor/jquery.min.js" %}><\/script>')</script>
    <script src='{% static "index/dist/js/bootstrap.min.js" %}'></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src='{% static "index/assets/js/ie10-viewport-bug-workaround.js" %}'></script>
  </body>
</html>

index/templates/index/main.html
{% extends 'index/index.html' %}

{% load staticfiles %}
{% block body %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">hey there!</h1>
            <p>
            </p>
        </div>
    </div>
      
    <div class="container">
        <section class="about-us">
            <h2 class="about-title">who are we?</h2>
            <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Eligendi similique culpa molestiae vero quos earum molestias eos eius consequuntur debitis omnis nemo deserunt doloremque nulla, 
            ipsum tenetur, inventore ipsam, officia reprehenderit distinctio voluptates voluptatem? Adipisci, nemo. 
            Corrupti officia quis id nulla voluptatibus officiis facilis? Architecto quis accusantium mollitia nulla delectus animi 
            reprehenderit voluptates, accusamus iusto fugiat natus quisquam neque laudantium quaerat maxime sed at atque exercitationem 
            harum dolore magnam quas sit!
            </p>
        </section>
    </div>
    <div class="simg1">
        <span class="section-header"> Section Two</span>
    </div>
      
    <div class="container services-section">
        <div class="container">
            <h2 class="services-title">What do we do?</h2>
            <div class="row rsection">
                <div class="col-md-4">
                    <span class="fa fa-cogs" style="font-size:48px"></span>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo. </p>
                </div>
                <div class="col-md-4">
                    <span class="	fa fa-code" style="font-size:48px"></span>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa fa-bar-chart" style="font-size:48px"></span>
                    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula.</p>
                </div>
            </div>
        </div>
    </div> <!-- /container -->
      
    <div class="simg2">
        <span class="section-header"> Section Three</span>
    </div>
      
    <div class="container-fluid portfolio-section">
        {% if index_list %}
            <h2 class="portfolio-title">what have we done?</h2>
            <div class="container-fluid">
                <div class="row">
                    {% for portfolio in index_list %}
                        <div class="col-md-4 proj-display">
                            <img src="{{ portfolio.project_cover_pic.url }}" alt="" class="proj-cover-img" style="max-width:100%;">
                            
                            <p class="proj-details" style="text-align: right;">
                                {{ portfolio.project_title }}
                                <span  class="	fa fa-bookmark-o" style="font-size:10px; padding:10px 0 10px 10px;"> 
                                {{ portfolio.project_type }}</span>
                            </p>
                            <p class="proj-links" style="text-align: right;">
                            <span><a href="{{ portfolio.project_link }}" class="btn-project" role="button">visit website</a></span>
                            <span><a href="{% url 'index:detail' portfolio.id %}" class="btn-project" role="button">view details <span class="fa fa-angle-double-right"></span></a></span>
                            <p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <h3>Sorry. No Projects Currently Available</h3>
        {% endif %}
    </div>
      
    <div class="simg3">
        <span class="section-header"> Section Three</span>
    </div>
    
{% endblock %}

index/templates/index/project.html
{% extends 'index/index.html' %}

{% block title %}
{{portfolio.project_title}} | immerDEV
{% endblock %}

{% load staticfiles %}

{% block body %}

<div class="project_header">
    <h4 class="project-title"> {{ portfolio.project_title }} </h4>
</div>

<div class="container">
    <div class="row project-details">
        <div class="col-md-8">
            <div class="container-fluid">
                <img src=" {{ portfolio.project_cover_pic.url }}" style="width:100%;" class="project-pc">
            </div>
        </div>
        <div class="col-md-4">
            <p class="client-name"> Client: {{ portfolio.client }} </p><hr>
            <p class="category"> Category: {{ portfolio.project_type }}<hr>
            <p class="project-desc"> {{portfolio.project_description}}</p><hr>
            <p><a href="{{portfolio.project_link }}">Visit Website</a></p>
        </div>
    </div>
</div>

{% endblock %}